import re
import os
import sys

# --- List of files to process ---
# Extracted from your error log
file_paths = [
    "./agencies/agency-features/agency-dashboard.mdx",
    "./agencies/agency-features/README.mdx",
    "./agencies/agency-features/agency-profile.mdx",
    "./agencies/agency-features/client-invite.mdx",
    "./agencies/agency-features/transfer-ownership.mdx",
    "./agencies/xano-for-agencies.mdx",
    "./ai-tools/mcp-servers/README.mdx",
    "./ai-tools/mcp-servers/connecting-clients.mdx",
    "./ai-tools/mcp-servers/mcp-functions.mdx",
    "./before-you-begin/key-concepts.mdx",
    "./before-you-begin/the-development-life-cycle.mdx",
    "./before-you-begin/using-these-docs.mdx",
    "./before-you-begin/navigating-xano.mdx",
    "./before-you-begin/set-up-a-free-xano-account.mdx",
    "./building-backend-features/emails.mdx",
    "./building-backend-features/custom-report-generation.mdx",
    "./before-you-begin/where-should-i-start.mdx",
    "./building-backend-features/chatbots.mdx",
    "./building-backend-features/fuzzy-search.mdx",
    "./building-backend-features/messaging.mdx",
    "./building-backend-features/user-authentication-and-user-data/oauth-sso.mdx",
    "./building-backend-features/user-authentication-and-user-data/restricting-access-rbac.mdx",
    "./building-backend-features/user-authentication-and-user-data/README.mdx",
    "./building-backend-features/user-authentication-and-user-data/separating-user-data.mdx",
    "./building-backend-features/webhooks.mdx",
    "./developer-api-deprecated.mdx",
    "./enterprise/enterprise-features/instance-activity.mdx",
    "./enterprise/enterprise-features/compliance-center.mdx",
    "./enterprise/enterprise-features/security-policy.mdx",
    "./enterprise/enterprise-features/microservices.mdx",
    "./enterprise/enterprise-features/rbac-role-based-access-control.mdx",
    "./enterprise/enterprise-features/tenant-center.mdx",
    "./file-storage/file-storage-in-xano.mdx",
    "./file-storage/private-file-storage.mdx",
    "./enterprise/enterprise-features/xano-link.mdx",
    "./instances/api-rate-limit.mdx",
    "./maintenance-monitoring-and-logging/instance-dashboard/README.mdx",
    "./maintenance-monitoring-and-logging/statement-explorer.mdx",
    "./maintenance-monitoring-and-logging/request-history.mdx",
    "./security/best-practices.mdx",
    "./realtime/realtime-in-webflow.mdx",
    "./realtime/realtime-in-xano.mdx",
    "./team-collaboration/branching-and-merging.mdx",
    "./team-collaboration/role-based-access-control-rbac.mdx",
    "./team-collaboration/realtime-collaboration.mdx",
    "./realtime/channel-permissions.mdx",
    "./testing-debugging/test-suites.mdx",
    "./testing-debugging/testing-and-debugging-function-stacks.mdx",
    "./testing-debugging/unit-tests.mdx",
    "./the-database/database-basics/database-views.mdx",
    "./the-database/database-basics/data-sources.mdx",
    "./the-database/database-basics/relationships.mdx",
    "./the-database/database-basics/export-and-sharing.mdx",
    "./team-collaboration/managing-team-members.mdx",
    "./the-database/database-performance-and-maintenance/indexing.mdx",
    "./the-database/database-basics/using-the-xano-database.mdx",
    "./the-database/database-performance-and-maintenance/README.mdx",
    "./the-database/database-performance-and-maintenance/maintenance.mdx",
    "./the-database/database-performance-and-maintenance/schema-versioning.mdx",
    "./the-database/designing-your-database.mdx",
    "./the-database/migrating-your-data/airtable-to-xano.mdx",
    "./the-database/migrating-your-data/csv-import-and-export.mdx",
    "./the-database/migrating-your-data/supabase-to-xano.mdx",
    "./the-function-stack/building-with-visual-development/README.mdx",
    "./the-function-stack/additional-features/README.mdx",
    "./the-function-stack/building-with-visual-development/background-tasks.mdx",
    "./the-function-stack/building-with-visual-development/configuring-expressions.mdx",
    "./the-function-stack/building-with-visual-development/apis/README.mdx",
    "./the-function-stack/building-with-visual-development/apis/swagger-openapi-documentation.mdx",
    "./the-function-stack/building-with-visual-development/custom-functions/README.mdx",
    "./the-function-stack/building-with-visual-development/custom-functions/async-functions.mdx",
    "./the-function-stack/building-with-visual-development/working-with-data.mdx",
    "./the-function-stack/building-with-visual-development/middleware.mdx",
    "./the-function-stack/building-with-visual-development/triggers.mdx",
    "./the-function-stack/data-types/expression.mdx",
    "./the-function-stack/data-types/timestamp.mdx",
    "./the-function-stack/environment-variables.mdx",
    "./the-function-stack/filters/README.mdx",
    "./the-function-stack/filters/array.mdx",
    "./the-function-stack/filters/comparison.mdx",
    "./the-function-stack/filters/manipulation.mdx",
    "./the-function-stack/filters/conversion.mdx",
    "./the-function-stack/filters/transform.mdx",
    "./the-function-stack/filters/security.mdx",
    "./the-function-stack/filters/math.mdx",
    "./the-function-stack/filters/timestamp.mdx",
    "./the-function-stack/filters/text.mdx",
    "./the-function-stack/functions/ai-tools.mdx",
    "./the-function-stack/functions/apis-and-lambdas/README.mdx",
    "./the-function-stack/functions/apis-and-lambdas/lambda-functions.mdx",
    "./the-function-stack/functions/apis-and-lambdas/external-api-request.mdx",
    "./the-function-stack/functions/apis-and-lambdas/realtime-functions.mdx",
    "./the-function-stack/functions/data-manipulation/README.mdx",
    "./the-function-stack/functions/data-manipulation/arrays.mdx",
    "./the-function-stack/functions/data-manipulation/conditional.mdx",
    "./the-function-stack/functions/data-manipulation/create-variable.mdx",
    "./the-function-stack/functions/data-manipulation/loops.mdx",
    "./the-function-stack/functions/data-manipulation/math.mdx",
    "./the-function-stack/functions/cloud-services.mdx",
    "./the-function-stack/functions/data-manipulation/switch.mdx",
    "./the-function-stack/functions/custom-functions.mdx",
    "./the-function-stack/functions/data-manipulation/update-variable.mdx",
    "./the-function-stack/functions/database-requests/README.mdx",
    "./the-function-stack/functions/database-requests/add-or-edit-record.mdx",
    "./the-function-stack/functions/database-requests/add-record.mdx",
    "./the-function-stack/functions/database-requests/delete-record.mdx",
    "./the-function-stack/functions/database-requests/edit-record.mdx",
    "./the-function-stack/functions/database-requests/direct-database-query.mdx",
    "./the-function-stack/functions/database-requests/external-database-query.mdx",
    "./the-function-stack/functions/database-requests/bulk-operations.mdx",
    "./the-function-stack/functions/database-requests/get-database-schema.mdx",
    "./the-function-stack/functions/database-requests/get-record.mdx",
    "./the-function-stack/functions/database-requests/patch-record.mdx",
    "./the-function-stack/functions/database-requests/database-transaction.mdx",
    "./the-function-stack/functions/database-requests/query-all-records/README.mdx",
    "./the-function-stack/functions/utility-functions.mdx",
    "./the-function-stack/functions/security.mdx",
    "./troubleshooting-and-support/error-reference.mdx",
    "./troubleshooting-and-support/getting-help/README.mdx",
    "./the-function-stack/functions/file-storage.mdx",
    "./troubleshooting-and-support/troubleshooting-performance/README.mdx",
    "./troubleshooting-and-support/troubleshooting-performance/when-everything-feels-slow.mdx",
    "./xano-ai/ai-database-assistant.mdx",
    "./troubleshooting-and-support/troubleshooting-performance/when-a-single-workflow-feels-slow.mdx",
    "./xano-ai/ai-lambda-assistant.mdx",
    "./xano-ai/ai-sql-assistant.mdx",
    "./xano-ai/building-a-backend-using-ai.mdx",
    "./xano-ai/get-started-assistant.mdx",
    "./xano-ai/streaming-apis.mdx",
    "./xano-actions/what-are-actions.mdx",
    "./xano-ai/template-engine.mdx",
    "./xano-features/advanced-back-end-features/developer-api-deprecated.mdx",
    "./xano-features/advanced-back-end-features/xano-link.mdx",
    "./xano-features/instance-settings/README.mdx",
    "./xano-features/instance-settings/backup-and-restore.mdx",
    "./xano-features/instance-settings/change-server-region.mdx",
    "./xano-ai/api-request-assistant.mdx",
    "./xano-features/instance-settings/security-policy.mdx",
    "./xano-features/metadata-api/README.mdx",
    "./xano-features/metadata-api/content.mdx",
    "./xano-features/instance-settings/static-ip-outgoing.mdx",
    "./xano-features/metadata-api/master-metadata-api.mdx",
    "./xano-features/metadata-api/file.mdx",
    "./xano-features/metadata-api/request-history.mdx",
    "./xano-features/metadata-api/tables-and-schema.mdx",
    "./xano-features/metadata-api/token-scopes-reference.mdx",
    "./xano-features/metadata-api/workspace-import-and-export.mdx",
    "./xanoscript/db/README.mdx",
    "./xanoscript/fs/README.mdx",
    "./xano-transform/using-xano-transform.mdx",
    "./xano-features/metadata-api/search.mdx",
    "./xanoscript/fs/filter-reference/README.mdx",
    "./xanoscript/db/field-type-reference.mdx",
    "./xanoscript/fs/filter-reference/array.mdx",
    "./xanoscript/fs/filter-reference/comparison.mdx",
    "./xanoscript/fs/filter-reference/manipulation.mdx",
    "./xanoscript/fs/filter-reference/security.mdx",
    "./xanoscript/fs/filter-reference/math.mdx",
    "./xanoscript/fs/filter-reference/text.mdx",
    "./xano-features/snippets.mdx",
    "./xanoscript/fs/filter-reference/timestamp.mdx",
    "./xanoscript/fs/filter-reference/transform.mdx",
    "./xanoscript/fs/function-reference/apis-and-lambdas.mdx",
    "./xanoscript/fs/function-reference/cloud-services/algolia.mdx",
    "./xanoscript/fs/function-reference/cloud-services/aws-opensearch.mdx",
    "./xanoscript/fs/function-reference/README.mdx",
    "./xanoscript/fs/function-reference/cloud-services/azure-blob-storage.mdx",
    "./xanoscript/fs/function-reference/cloud-services/elasticsearch.mdx",
    "./xanoscript/fs/function-reference/cloud-services/google-cloud-storage.mdx",
    "./xanoscript/fs/function-reference/cloud-services/aws-s3.mdx",
    "./xanoscript/fs/function-reference/data-caching-redis.mdx",
    "./xanoscript/fs/function-reference/data-manipulation/README.mdx",
    "./xanoscript/fs/function-reference/data-manipulation/loops.mdx",
    "./xanoscript/fs/function-reference/data-manipulation/arrays.mdx",
    "./xanoscript/fs/function-reference/data-manipulation/math.mdx",
    "./xanoscript/fs/function-reference/data-manipulation/objects.mdx",
    "./xanoscript/fs/function-reference/data-manipulation/conditionals.mdx",
    "./xanoscript/fs/function-reference/data-manipulation/variables.mdx",
    "./xanoscript/fs/function-reference/database-operations.mdx",
    "./xanoscript/fs/function-reference/data-manipulation/text.mdx",
    "./xanoscript/fs/function-reference/file-storage.mdx",
    "./xanoscript/fs/function-reference/security.mdx",
    "./xanoscript/fs/function-reference/utility-functions.mdx",
    "./xanoscript/fs/input-types-reference.mdx",
    "./xanoscript/ts.mdx",
    "./your-xano-account/billing.mdx",
    "./xanoscript/keyconcepts.mdx",
    "./xanoscript/introduction-to-xanoscript.mdx",
    "./snippets/action-postmark-send-batch-emails.mdx",
    "./snippets/action-block-template.mdx",
    "./snippets/action-postmark-send-email-with-template.mdx",
    "./snippets/action-postmark-send-single-email.mdx",
    "./snippets/action-send-slack-message.mdx",
    "./snippets/action-send-whatsapp-message.mdx",
    "./snippets/ai-request-assistant.mdx",
    "./snippets/action-send-email-using-brevo.mdx",
    "./your-xano-account/referrals-and-commissions.mdx",
    "./snippets/array-add-to-beginning.mdx",
    "./snippets/array-merge.mdx",
    "./snippets/aws-opensearch-search-query.mdx",
    "./snippets/array-remove-from-end-of.mdx",
    "./snippets/bitwise-and-number.mdx",
    "./snippets/ba-bookstore-set-up-database-tables.mdx",
    "./snippets/clearing-request-history.mdx",
    "./snippets/definition-of-an-api.mdx",
    "./snippets/bulk-operations.mdx",
    "./snippets/exporting-table-data-as-csv.mdx",
    "./snippets/enabling-the-marketplace.mdx",
    "./snippets/filter-note.mdx",
    "./snippets/filter-template-not-xs.mdx",
    "./snippets/expression-builder.mdx",
    "./snippets/find-all-elements.mdx",
    "./snippets/find-first-element-in.mdx",
    "./snippets/find-first-element-index-in (1).mdx",
    "./snippets/find-first-element-index-in (2).mdx",
    "./snippets/find-first-element-index-in.mdx",
    "./snippets/first_notempty.mdx",
    "./snippets/function-descriptions.mdx",
    "./snippets/get-keys (1).mdx",
    "./snippets/get-keys.mdx",
    "./snippets/get-values.mdx",
    "./snippets/metadata-api-account.mdx",
    "./snippets/metadata-api-api-groups.mdx",
    "./snippets/metadata-api-apis.mdx",
    "./snippets/metadata-api-files.mdx",
    "./snippets/metadata-api-functions.mdx",
    "./snippets/metadata-api-instances.mdx",
    "./snippets/metadata-api-realtime.mdx",
    "./snippets/metadata-api-snippets.mdx",
    "./snippets/metadata-api-workspace.mdx",
    "./snippets/metadata-api-tasks.mdx",
    "./snippets/name.mdx",
    "./snippets/query-all-records.mdx",
    "./snippets/rate-limit.mdx",
    "./snippets/release-rollout-note.mdx",
    "./snippets/response-customization.mdx",
    "./snippets/metadata-api-tables.mdx",
    "./snippets/safe-mode.mdx",
    "./snippets/schedule.mdx",
    "./snippets/security-policy.mdx",
    "./snippets/swagger-defining-examples.mdx",
    "./snippets/sql-injection.mdx",
    "./snippets/using-the-ai-database-assistant.mdx",
    "./snippets/using-the-ai-sql-assistant.mdx",
    "./snippets/xano-ai-explainer.mdx",
    "./snippets/template-engine.mdx",
    "./snippets/using-the-lambda-ai-assistant.mdx",
    "./snippets/xano-ai-feedback-instructions.mdx",
    "./snippets/xs-add-number.mdx",
    "./snippets/xs-add-or-edit-record.mdx",
    "./snippets/xs-add-record.mdx",
    "./snippets/xs-add-to-beginning-of-list.mdx",
    "./snippets/xs-add-to-end-of-list.mdx",
    "./snippets/xs-algolia-request.mdx",
    "./snippets/xs-append-text.mdx",
    "./snippets/xs-array-find-first-element-index-in.mdx",
    "./snippets/xs-array-has-any-element.mdx",
    "./snippets/xs-array-has-every-element.mdx",
    "./snippets/xs-array-remove-from-end-of.mdx",
    "./snippets/xs-aws-opensearch-document-crud.mdx",
    "./snippets/xs-array-add-to-end.mdx",
    "./snippets/xs-async-await.mdx",
    "./snippets/xs-aws-opensearch-request.mdx",
    "./snippets/xs-aws-s3-get-signed-url-of.mdx",
    "./snippets/xs-aws-s3-get-file-metadata.mdx",
    "./snippets/xs-array-remove-from-beginning-of.mdx",
    "./snippets/xs-aws-s3-list-directory-of.mdx",
    "./snippets/xs-aws-s3-upload-file-to.mdx",
    "./snippets/xs-aws-s3-delete-file.mdx",
    "./snippets/xs-aws-s3-create-var-from-file-resource.mdx",
    "./snippets/xs-aws-s3-read-file.mdx",
    "./snippets/xs-azure-blob-storage-get-signed-url.mdx",
    "./snippets/xs-azure-delete-file.mdx",
    "./snippets/xs-azure-create-var-from-file-resource.mdx",
    "./snippets/xs-azure-list-directory-of.mdx",
    "./snippets/xs-azure-upload-file.mdx",
    "./snippets/xs-beta-alpha-notice.mdx",
    "./snippets/xs-bitwise-or-number.mdx",
    "./snippets/xs-bulk-operations.mdx",
    "./snippets/xs-bulk-update-record.mdx",
    "./snippets/xs-break-out-of-loop.mdx",
    "./snippets/xs-azure-blob-storage-get-file-metadata.mdx",
    "./snippets/xs-calculate-distance.mdx",
    "./snippets/xs-conditional.mdx",
    "./snippets/xs-continue-to-next-iteration-of-loop.mdx",
    "./snippets/xs-create-attachment-metadata.mdx",
    "./snippets/xs-bitwise-xor-number.mdx",
    "./snippets/xs-create-audio-metadata.mdx",
    "./snippets/xs-create-auth-token.mdx",
    "./snippets/xs-create-eliptic-curve-key.mdx",
    "./snippets/xs-create-file-resource.mdx",
    "./snippets/xs-create-image-metadata.mdx",
    "./snippets/xs-create-rsa-key.mdx",
    "./snippets/xs-create-variable.mdx",
    "./snippets/xs-create-secret-key.mdx",
    "./snippets/xs-csv-stream.mdx",
    "./snippets/xs-create-video-metadata.mdx",
    "./snippets/xs-db-attachment.mdx",
    "./snippets/xs-db-audio.mdx",
    "./snippets/xs-db-bool.mdx",
    "./snippets/xs-db-date.mdx",
    "./snippets/xs-db-decimal.mdx",
    "./snippets/xs-db-email.mdx",
    "./snippets/xs-db-enum.mdx",
    "./snippets/xs-db-geo_path.mdx",
    "./snippets/xs-db-geo_multipoint.mdx",
    "./snippets/xs-db-geo_path_collection.mdx",
    "./snippets/xs-db-geo_polygon.mdx",
    "./snippets/xs-db-geo_polygon_collection.mdx",
    "./snippets/xs-db-image.mdx",
    "./snippets/xs-db-json.mdx",
    "./snippets/xs-db-integer.mdx",
    "./snippets/xs-db-object.mdx",
    "./snippets/xs-db-text.mdx",
    "./snippets/xs-db-password.mdx",
    "./snippets/xs-db-uuid.mdx",
    "./snippets/xs-db-video.mdx",
    "./snippets/xs-db-timestamp.mdx",
    "./snippets/xs-db.mdx",
    "./snippets/xs-db-vector.mdx",
    "./snippets/xs-decrement-cache-value.mdx",
    "./snippets/xs-debug-log.mdx",
    "./snippets/xs-delete-cache-value.mdx",
    "./snippets/xs-delete-file.mdx",
    "./snippets/xs-divide-number.mdx",
    "./snippets/xs-delete-record.mdx",
    "./snippets/xs-elasticsearch-document.mdx",
    "./snippets/xs-elasticsearch-search-query.mdx",
    "./snippets/xs-elasticsearch-request.mdx",
    "./snippets/xs-edit-record.mdx",
    "./snippets/xs-ends-with.mdx",
    "./snippets/xs-field-type-template.mdx",
    "./snippets/xs-external-api-request.mdx",
    "./snippets/xs-filter (2).mdx",
    "./snippets/xs-filter (3).mdx",
    "./snippets/xs-filter (4).mdx",
    "./snippets/xs-filter (1).mdx",
    "./snippets/xs-filter-abs.mdx",
    "./snippets/xs-filter-acos.mdx",
    "./snippets/xs-filter-acosh.mdx",
    "./snippets/xs-filter-add.mdx",
    "./snippets/xs-filter-array_diff.mdx",
    "./snippets/xs-filter-append.mdx",
    "./snippets/xs-filter-addslashes.mdx",
    "./snippets/xs-filter-array_diff_assoc.mdx",
    "./snippets/xs-filter-array_fill.mdx",
    "./snippets/xs-filter-array_entries.mdx",
    "./snippets/xs-filter-array_fill_keys.mdx",
    "./snippets/xs-filter-array_intersect.mdx",
    "./snippets/xs-filter-array_keys.mdx",
    "./snippets/xs-filter-array_intersect_assoc.mdx",
    "./snippets/xs-filter-array_merge.mdx",
    "./snippets/xs-filter-array_merge_recursive.mdx",
    "./snippets/xs-filter-array_pop.mdx",
    "./snippets/xs-filter-array_remove.mdx",
    "./snippets/xs-filter-array_push.mdx",
    "./snippets/xs-filter-array_shuffle.mdx",
    "./snippets/xs-filter-array_shift.mdx",
    "./snippets/xs-filter-array_unshift.mdx",
    "./snippets/xs-filter-array_values.mdx",
    "./snippets/xs-filter-asin.mdx",
    "./snippets/xs-filter-array_slice.mdx",
    "./snippets/xs-filter-atan.mdx",
    "./snippets/xs-filter-asinh.mdx",
    "./snippets/xs-filter-atanh.mdx",
    "./snippets/xs-filter-avg.mdx",
    "./snippets/xs-filter-base64_decode.mdx",
    "./snippets/xs-filter-base64_encode.mdx",
    "./snippets/xs-filter-base64_decode_urlsafe.mdx",
    "./snippets/xs-filter-base64_encode_urlsafe.mdx",
    "./snippets/xs-filter-base_convert.mdx",
    "./snippets/xs-filter-bin2hex.mdx",
    "./snippets/xs-filter-bindec.mdx",
    "./snippets/xs-filter-bitwise_and.mdx",
    "./snippets/xs-filter-bitwise_or.mdx",
    "./snippets/xs-filter-bitwise_not.mdx",
    "./snippets/xs-filter-bitwise_xor.mdx",
    "./snippets/xs-filter-capitalize.mdx",
    "./snippets/xs-filter-ceil.mdx",
    "./snippets/xs-filter-concat.mdx",
    "./snippets/xs-filter-contains.mdx",
    "./snippets/xs-filter-convert_encoding.mdx",
    "./snippets/xs-filter-create_object.mdx",
    "./snippets/xs-filter-create_object_from_entries.mdx",
    "./snippets/xs-filter-crypto_jwe_decode.mdx",
    "./snippets/xs-filter-crypto_jwe_encode.mdx",
    "./snippets/xs-filter-crypto_jws_decode.mdx",
    "./snippets/xs-filter-crypto_jws_encode.mdx",
    "./snippets/xs-filter-cos.mdx",
    "./snippets/xs-filter-count.mdx",
    "./snippets/xs-filter-csv_decode.mdx",
    "./snippets/xs-filter-csv_create.mdx",
    "./snippets/xs-filter-csv_parse.mdx",
    "./snippets/xs-filter-decbin.mdx",
    "./snippets/xs-filter-dechex.mdx",
    "./snippets/xs-filter-decoct.mdx",
    "./snippets/xs-filter-decrypt.mdx",
    "./snippets/xs-filter-div.mdx",
    "./snippets/xs-filter-deg2rad.mdx",
    "./snippets/xs-filter-empty.mdx",
    "./snippets/xs-filter-encrypt.mdx",
    "./snippets/xs-filter-ends_with.mdx",
    "./snippets/xs-filter-epochms_add_ms.mdx",
    "./snippets/xs-filter-epochms_add_secs.mdx",
    "./snippets/xs-filter-epochms_date.mdx",
    "./snippets/xs-filter-epochms_from_format.mdx",
    "./snippets/xs-filter-epochms_transform.mdx",
    "./snippets/xs-filter-eq.mdx",
    "./snippets/xs-filter-escape.mdx",
    "./snippets/xs-filter-every.mdx",
    "./snippets/xs-filter-exp.mdx",
    "./snippets/xs-filter-even.mdx",
    "./snippets/xs-filter-filter.mdx",
    "./snippets/xs-filter-filter_empty.mdx",
    "./snippets/xs-filter-find.mdx",
    "./snippets/xs-filter-first.mdx",
    "./snippets/xs-filter-findindex.mdx",
    "./snippets/xs-filter-first_notempty.mdx",
    "./snippets/xs-filter-first_notnull.mdx",
    "./snippets/xs-filter-flatten.mdx",
    "./snippets/xs-filter-floor.mdx",
    "./snippets/xs-filter-from_utf8.mdx",
    "./snippets/xs-filter-gt.mdx",
    "./snippets/xs-filter-fsort.mdx",
    "./snippets/xs-filter-has.mdx",
    "./snippets/xs-filter-hex2bin.mdx",
    "./snippets/xs-filter-gte.mdx",
    "./snippets/xs-filter-hexdec.mdx",
    "./snippets/xs-filter-icontains.mdx",
    "./snippets/xs-filter-hmac_sha1-hmac_sha256-hmac_384-hmac_512.mdx",
    "./snippets/xs-filter-get.mdx",
    "./snippets/xs-filter-iends_with.mdx",
    "./snippets/xs-filter-iindex.mdx",
    "./snippets/xs-filter-in.mdx",
    "./snippets/xs-filter-index.mdx",
    "./snippets/xs-filter-is_array.mdx",
    "./snippets/xs-filter-is_decimal.mdx",
    "./snippets/xs-filter-is_int.mdx",
    "./snippets/xs-filter-is_bool.mdx",
    "./snippets/xs-filter-is_object.mdx",
    "./snippets/xs-filter-is_text.mdx",
    "./snippets/xs-filter-istarts_with.mdx",
    "./snippets/xs-filter-join.mdx",
    "./snippets/xs-filter-json_decode.mdx",
    "./snippets/xs-filter-json_encode.mdx",
    "./snippets/xs-filter-last.mdx",
    "./snippets/xs-filter-log.mdx",
    "./snippets/xs-filter-ln.mdx",
    "./snippets/xs-filter-log10.mdx",
    "./snippets/xs-filter-index_by.mdx",
    "./snippets/xs-filter-lower.mdx",
    "./snippets/xs-filter-lambda.mdx",
    "./snippets/xs-filter-lt.mdx",
    "./snippets/xs-filter-ltrim.mdx",
    "./snippets/xs-filter-map.mdx",
    "./snippets/xs-filter-lte.mdx",
    "./snippets/xs-filter-mod.mdx",
    "./snippets/xs-filter-md5.mdx",
    "./snippets/xs-filter-ne.mdx",
    "./snippets/xs-filter-not.mdx",
    "./snippets/xs-filter-mul.mdx",
    "./snippets/xs-filter-null.mdx",
    "./snippets/xs-filter-octdec.mdx",
    "./snippets/xs-filter-number_format.mdx",
    "./snippets/xs-filter-pick.mdx",
    "./snippets/xs-filter-prepend.mdx",
    "./snippets/xs-filter-pow.mdx",
    "./snippets/xs-filter-rad2deg.mdx",
    "./snippets/xs-filter-range.mdx",
    "./snippets/xs-filter-reduce.mdx",
    "./snippets/xs-filter-regex_match.mdx",
    "./snippets/xs-filter-product.mdx",
    "./snippets/xs-filter-querystring_parse.mdx",
    "./snippets/xs-filter-regex_match_all.mdx",
    "./snippets/xs-filter-regex_quote.mdx",
    "./snippets/xs-filter-regex_test.mdx",
    "./snippets/xs-filter-regex_replace.mdx",
    "./snippets/xs-filter-reverse.mdx",
    "./snippets/xs-filter-odd.mdx",
    "./snippets/xs-filter-rtrim.mdx",
    "./snippets/xs-filter-secureid_decode.mdx",
    "./snippets/xs-filter-set_ifnotempty.mdx",
    "./snippets/xs-filter-secureid_encode.mdx",
    "./snippets/xs-filter-safe_array.mdx",
    "./snippets/xs-filter-set_ifnotnull.mdx",
    "./snippets/xs-filter-set.mdx",
    "./snippets/xs-filter-shuffle.mdx",
    "./snippets/xs-filter-round.mdx",
    "./snippets/xs-filter-sin.mdx",
    "./snippets/xs-filter-sha1-sha256-sha384-sha512.mdx",
    "./snippets/xs-filter-split.mdx",
    "./snippets/xs-filter-sprintf.mdx",
    "./snippets/xs-filter-sqrt.mdx",
    "./snippets/xs-filter-starts_with.mdx",
    "./snippets/xs-filter-strip_tags.mdx",
    "./snippets/xs-filter-strip_accents.mdx",
    "./snippets/xs-filter-strlen.mdx",
    "./snippets/xs-filter-sub.mdx",
    "./snippets/xs-filter-substr.mdx",
    "./snippets/xs-filter-sum.mdx",
    "./snippets/xs-filter-tan.mdx",
    "./snippets/xs-filter-template.mdx",
    "./snippets/xs-filter-to_bool.mdx",
    "./snippets/xs-filter-to_decimal.mdx",
    "./snippets/xs-filter-to_epoch_day.mdx",
    "./snippets/xs-filter-to_epoch_hour.mdx",
    "./snippets/xs-filter-to_epoch_minute.mdx",
    "./snippets/xs-filter-to_epoch_ms.mdx",
    "./snippets/xs-filter-to_epoch_sec.mdx",
    "./snippets/xs-filter-to_expr.mdx",
    "./snippets/xs-filter-to_epochms.mdx",
    "./snippets/xs-filter-to_int.mdx",
    "./snippets/xs-filter-to_text.mdx",
    "./snippets/xs-filter-to_utf8.mdx",
    "./snippets/xs-filter-trim.mdx",
    "./snippets/xs-filter-unique.mdx",
    "./snippets/xs-filter-uid.mdx",
    "./snippets/xs-filter-transform.mdx",
    "./snippets/xs-filter-unpick.mdx",
    "./snippets/xs-filter-unset.mdx",
    "./snippets/xs-filter-upper.mdx",
    "./snippets/xs-filter-url_addarg.mdx",
    "./snippets/xs-filter-url_decode.mdx",
    "./snippets/xs-filter-url_delarg.mdx",
    "./snippets/xs-filter-url_decode_rfc3986.mdx",
    "./snippets/xs-filter-url_encode.mdx",
    "./snippets/xs-filter-url_encode_rfc3986.mdx",
    "./snippets/xs-filter-url_getarg.mdx",
    "./snippets/xs-filter-url_hasarg.mdx",
    "./snippets/xs-filter-url_parse.mdx",
    "./snippets/xs-filter-yaml_decode.mdx",
    "./snippets/xs-filter.mdx",
    "./snippets/xs-for-loop.mdx",
    "./snippets/xs-for-each-loop.mdx",
    "./snippets/xs-filter-xml_decode.mdx",
    "./snippets/xs-function-template.mdx",
    "./snippets/xs-filter-uuid4.mdx",
    "./snippets/xs-gcs-delete.mdx",
    "./snippets/xs-gcs-get-signed-url.mdx",
    "./snippets/xs-gcs-list-dir.mdx",
    "./snippets/xs-gcs-upload-file.mdx",
    "./snippets/xs-generate-password.mdx",
    "./snippets/xs-generate-random-bytes.mdx",
    "./snippets/xs-generate-uuid.mdx",
    "./snippets/xs-generate-random-number.mdx",
    "./snippets/xs-get-all-input.mdx",
    "./snippets/xs-get-all-raw-input (1).mdx",
    "./snippets/xs-get-all-raw-input.mdx",
    "./snippets/xs-get-all-variables.mdx",
    "./snippets/xs-get-cache-keys.mdx",
    "./snippets/xs-get-elements-from-list.mdx",
    "./snippets/xs-get-cache-value.mdx",
    "./snippets/xs-get-environment-variables.mdx",
    "./snippets/xs-get-file-resource-data.mdx",
    "./snippets/xs-get-length-of-list.mdx",
    "./snippets/xs-google-cloud-storage-create-var-from-file-resource.mdx",
    "./snippets/xs-google-cloud-storage-get-file-metadata.mdx",
    "./snippets/xs-group.mdx",
    "./snippets/xs-has-record.mdx",
    "./snippets/xs-has-cache-value.mdx",
    "./snippets/xs-has-record (1).mdx",
    "./snippets/xs-get-record.mdx",
    "./snippets/xs-increment-cache-value.mdx",
    "./snippets/xs-jsonl-stream.mdx",
    "./snippets/xs-ip-address-lookup.mdx",
    "./snippets/xs-lambda.mdx",
    "./snippets/xs-left-trim.mdx",
    "./snippets/xs-modulus-number.mdx",
    "./snippets/xs-multiply-number.mdx",
    "./snippets/xs-patch.mdx",
    "./snippets/xs-rate-limit.mdx",
    "./snippets/xs-prepend-text.mdx",
    "./snippets/xs-precondition.mdx",
    "./snippets/xs-query-all-records.mdx",
    "./snippets/xs-remove-from-beginning-of-list.mdx",
    "./snippets/xs-realtime-event.mdx",
    "./snippets/xs-remove-from-end-of-list.mdx",
    "./snippets/xs-remove-from-list.mdx",
    "./snippets/xs-return.mdx",
    "./snippets/xs-set-cache-value.mdx",
    "./snippets/xs-sign-private-file-url.mdx",
    "./snippets/xs-sleep.mdx",
    "./snippets/xs-starts-with.mdx",
    "./snippets/xs-streaming-api-request.mdx",
    "./snippets/xs-stop-and-debug.mdx",
    "./snippets/xs-set-http-header.mdx",
    "./snippets/xs-streaming-api-response.mdx",
    "./snippets/xs-subtract-number.mdx",
    "./snippets/xs-template-engine.mdx",
    "./snippets/xs-text-contains.mdx",
    "./snippets/xs-text-right-trim.mdx",
    "./snippets/xs-text-trim.mdx",
    "./snippets/xs-update-variable.mdx",
    "./snippets/xs-set-data-source.mdx",
    "./snippets/xs-using-functions.mdx",
    "./snippets/xs-validate-password.mdx",
    "./snippets/xs-while-loop.mdx",
]

# Regex to find <img> tags not ending with />
# (?i) makes it case-insensitive
# \s+ matches one or more spaces
# [^>]*? matches any character except '>', non-greedily
# (?<!/) is a negative lookbehind, ensuring the char before > is not /
img_regex = re.compile(r'(?i)(<img\s+[^>]*?)(?<!/)>')

# Regex to find <br> tags (case-insensitive)
br_regex = re.compile(r'(?i)<br>')

# Counter for modified files
modified_count = 0
error_count = 0

print("--- Starting MDX Fix Script ---")
print("🛑 IMPORTANT: Ensure you have backed up your files before proceeding!")
print("This script will attempt to fix non-self-closing <img> and <br> tags.")
print("Acorn/JavaScript errors need manual review.\n")

# --- Process each file ---
for filepath in file_paths:
    if not os.path.exists(filepath):
        print(f"⚠️ Warning: File not found, skipping: {filepath}")
        error_count += 1
        continue

    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        original_content = content # Keep a copy for comparison

        # Fix <img> tags: replace '>' with ' />' if not already preceded by '/'
        content = img_regex.sub(r'\1 />', content)

        # Fix <br> tags: replace '<br>' with '<br />'
        content = br_regex.sub(r'<br />', content)

        # Only write back if changes were actually made
        if content != original_content:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"✅ Fixed tags in: {filepath}")
            modified_count += 1
        else:
            # If only Acorn errors exist for this file, no tag changes will be made here
            # print(f"ℹ️ No <img> or <br> tag changes needed for: {filepath}")
            pass # Avoid printing too much for unchanged files unless debugging

    except Exception as e:
        print(f"❌ Error processing file {filepath}: {e}")
        error_count += 1

print("\n--- Script Finished ---")
print(f"Processed {len(file_paths)} file paths.")
print(f"Modified {modified_count} files.")
print(f"Encountered {error_count} errors (file not found or processing error).")
print("\nReminder: Please manually review files that had 'Acorn' or other syntax errors.")
print("Re-run the Mintlify command to check if the fixed errors are resolved.")